In [1]:
import numpy as np

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5]

5

In [7]:
arr[5:8]

array([5, 6, 7])

In [8]:
arr[5:8] = 12

In [9]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [11]:
arr2d = np.array ([[1,2,3,4],[5,6,7,8,],[9,10,11,12],[13,14,15,16]])

In [12]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [13]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [15]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [16]:
arr2d[3,2]

15

In [17]:
arr2d[:2,1:3] = 0

In [18]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
names = np.array(["Jihyeon","Minkyu","Eunu","Jihyeon","Hyeonu","Minkyu","Kilho"])
data = np.random.randn(7,4)

In [22]:
names

array(['Jihyeon', 'Minkyu', 'Eunu', 'Jihyeon', 'Hyeonu', 'Minkyu',
       'Kilho'], dtype='<U7')

In [23]:
data

array([[-1.16933846,  0.3704945 , -0.23027139,  0.80595752],
       [-0.72157449,  0.79506438,  0.71026109,  0.38985423],
       [ 0.13618305, -0.28667006, -1.63845386, -0.58528284],
       [ 0.77229787, -1.09114335, -1.27661611, -0.02696138],
       [ 1.91699071, -0.53548941,  0.29261181,  0.83203298],
       [-0.9517439 , -0.39494298,  0.52920162, -1.27321979],
       [-0.91566321,  0.57964723,  1.97828483, -1.136858  ]])

In [24]:
names == "Jihyeon"

array([ True, False, False,  True, False, False, False])

In [25]:
data[names == "Jihyeon",:]

array([[-1.16933846,  0.3704945 , -0.23027139,  0.80595752],
       [ 0.77229787, -1.09114335, -1.27661611, -0.02696138]])

In [26]:
data[names == "Minkyu",:]

array([[-0.72157449,  0.79506438,  0.71026109,  0.38985423],
       [-0.9517439 , -0.39494298,  0.52920162, -1.27321979]])

In [27]:
data[(names == "Jihyeon")|(names == "Minkyu"),:]

array([[-1.16933846,  0.3704945 , -0.23027139,  0.80595752],
       [-0.72157449,  0.79506438,  0.71026109,  0.38985423],
       [ 0.77229787, -1.09114335, -1.27661611, -0.02696138],
       [-0.9517439 , -0.39494298,  0.52920162, -1.27321979]])

In [28]:
data[:,3]

array([ 0.80595752,  0.38985423, -0.58528284, -0.02696138,  0.83203298,
       -1.27321979, -1.136858  ])

In [29]:
data[:,3]<0

array([False, False,  True,  True, False,  True,  True])

In [31]:
data[data[:,3]<0 , :]

array([[ 0.13618305, -0.28667006, -1.63845386, -0.58528284],
       [ 0.77229787, -1.09114335, -1.27661611, -0.02696138],
       [-0.9517439 , -0.39494298,  0.52920162, -1.27321979],
       [-0.91566321,  0.57964723,  1.97828483, -1.136858  ]])

In [32]:
data[data[:,3]<0 , :] = 0

In [33]:
data

array([[-1.16933846,  0.3704945 , -0.23027139,  0.80595752],
       [-0.72157449,  0.79506438,  0.71026109,  0.38985423],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.91699071, -0.53548941,  0.29261181,  0.83203298],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])