In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [6]:
x=np.random.randn(8)
y=np.random.randn(8)

In [7]:
x

array([-0.26275521, -0.61908492, -0.58444357,  0.01556667, -0.22498728,
        1.57306212, -0.13100209,  0.2928574 ])

In [8]:
y

array([ 0.23089652, -0.3161978 , -0.51333782,  2.07334421,  0.14880048,
        1.142573  , -0.45428084,  0.18943261])

In [9]:
np.maximum(x,y)

array([ 0.23089652, -0.3161978 , -0.51333782,  2.07334421,  0.14880048,
        1.57306212, -0.13100209,  0.2928574 ])

In [10]:
arr = np.random.randn(5,4)

In [11]:
arr

array([[-0.57740035,  1.38300897, -0.91029239,  1.21309034],
       [-1.02332439, -1.12474972,  1.88127879, -1.38049196],
       [-1.57342441, -0.81490794, -0.45384403,  0.04588368],
       [-0.77157354, -0.58084443,  0.71411327, -0.45162414],
       [-0.14789439, -0.56196555,  0.2169135 ,  2.33416151]])

In [12]:
arr.sum()

-2.5838871879510825

In [13]:
arr.mean()

-0.12919435939755414

In [14]:
arr.sum(axis=0)

array([-4.09361709, -1.69945867,  1.44816914,  1.76101944])

In [15]:
arr.sum(axis=1)

array([ 1.10840657, -1.64728728, -2.7962927 , -1.08992884,  1.84121507])

In [16]:
arr > 0

array([[False,  True, False,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [17]:
(arr > 0).sum()

7

In [18]:
arr = np.random.randn(8)

In [19]:
arr

array([ 0.95273398,  1.58653145, -1.22152808,  0.95740078, -0.93567436,
       -0.50258675,  1.00704883,  2.1235772 ])

In [20]:
np.sort(arr)

array([-1.22152808, -0.93567436, -0.50258675,  0.95273398,  0.95740078,
        1.00704883,  1.58653145,  2.1235772 ])

In [23]:
np.sort(arr)[::-1]

array([ 2.1235772 ,  1.58653145,  1.00704883,  0.95740078,  0.95273398,
       -0.50258675, -0.93567436, -1.22152808])

In [24]:
arr = np.random.randn(5,3)

In [25]:
arr

array([[ 1.08311584, -0.80282828,  0.14042954],
       [ 0.48294241, -0.13647795,  1.64083104],
       [-0.80709198,  1.03600475, -0.3115955 ],
       [ 0.33133693,  0.38269814,  1.00914184],
       [ 1.01327042,  0.79396148, -1.35584305]])

In [26]:
np.sort(arr, axis=0)

array([[-0.80709198, -0.80282828, -1.35584305],
       [ 0.33133693, -0.13647795, -0.3115955 ],
       [ 0.48294241,  0.38269814,  0.14042954],
       [ 1.01327042,  0.79396148,  1.00914184],
       [ 1.08311584,  1.03600475,  1.64083104]])

In [27]:
np.sort(arr, axis=1)

array([[-0.80282828,  0.14042954,  1.08311584],
       [-0.13647795,  0.48294241,  1.64083104],
       [-0.80709198, -0.3115955 ,  1.03600475],
       [ 0.33133693,  0.38269814,  1.00914184],
       [-1.35584305,  0.79396148,  1.01327042]])

In [28]:
large_arr = np.random.randn(150)

In [29]:
large_arr

array([ 0.4985614 , -0.59570558, -0.41672652, -1.97396803, -0.75106266,
       -1.39248444, -0.80432961, -1.07976738, -0.68950504, -0.05041857,
        1.87235057, -0.12436237, -0.42490475,  0.10630298,  0.6531737 ,
       -0.16880697, -0.1131915 , -0.04829337,  0.77487668,  1.16766625,
        0.92566477, -0.11701713, -0.81769251, -1.97270836, -0.01555147,
        0.52272794, -1.45693328,  1.40036524, -0.06504748,  0.14614772,
        0.77479236, -2.07301587,  1.21244997, -0.51485295, -1.55015048,
       -0.17790911,  0.07799407, -1.60180624,  0.26323576,  0.63700394,
        0.24266432,  0.19694884, -0.29504115, -0.88890666,  1.06152676,
        0.50470865, -0.50702179,  0.36478026,  0.09943171, -0.22918923,
        0.89360564,  0.73024177,  0.02005878,  1.20527469, -0.65133656,
        1.69555115, -0.05380874,  0.12003202,  0.97979339, -1.41649501,
       -0.44230489, -1.19643343, -0.9260645 ,  1.04413842, -2.4532588 ,
        0.97219139, -0.33870176, -0.32784253,  1.60948776,  0.57

In [30]:
np.sort(large_arr)[::-1][int(0.05) * len(large_arr)]

3.7790081224851853

In [31]:
names = np.array(["Jihyeon","Minkyu","Eunu","Jihyeon","Hyeonu","Minkyu","Kilho"])
ints = np.array([3,3,3,2,2,1,1,4,4])

In [33]:
np.unique(names)

array(['Eunu', 'Hyeonu', 'Jihyeon', 'Kilho', 'Minkyu'], dtype='<U7')

In [34]:
np.unique(ints)

array([1, 2, 3, 4])